import { colors } from '../constants/colors'
import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.bg },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingTop: 12,
    paddingBottom: 8,
  },
  headerTitle: { fontSize: 20, fontWeight: '700', color: colors.text, letterSpacing: 1 },
  statusPill: {
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 20,
    backgroundColor: colors.surface,
    borderWidth: 1,
    borderColor: colors.border,
  },
  statusPillReady: { borderColor: '#2d6a2d' },
  statusPillSleeping: { borderColor: '#7a6a1a' },
  statusPillError: { borderColor: '#6a2d2d' },
  statusPillText: { fontSize: 11, color: colors.muted },
  tabs: {
    flexDirection: 'row',
    marginHorizontal: 20,
    marginBottom: 12,
    backgroundColor: colors.surface,
    borderRadius: 12,
    padding: 4,
  },
  tab: { flex: 1, paddingVertical: 8, borderRadius: 10, alignItems: 'center' },
  tabActive: { backgroundColor: colors.accentDim },
  tabText: { color: colors.muted, fontSize: 13, fontWeight: '600' },
  tabTextActive: { color: colors.text },
  stepContent: {
    flexGrow: 1,
    paddingHorizontal: 20,
    paddingTop: 8,
    paddingBottom: 40,
  },
  textArea: {
    width: '100%',
    minHeight: 160,
    backgroundColor: colors.surface,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    color: colors.text,
    padding: 16,
    fontSize: 16,
    lineHeight: 24,
    textAlignVertical: 'top',
    marginBottom: 20,
  },
  sectionLabel: {
    alignSelf: 'flex-start',
    color: colors.muted,
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 1.5,
    textTransform: 'uppercase',
    marginBottom: 10,
  },
  chipsRow: { marginBottom: 24 },
  chip: {
    width: '48%',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 8,
    backgroundColor: '#1e1e2e',
  },
  chipText: { color: colors.text, fontSize: 12, lineHeight: 17 },
  primaryButton: {
    width: '100%',
    backgroundColor: colors.accent,
    borderRadius: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginTop: 8,
  },
  primaryButtonDisabled: { opacity: 0.4 },
  primaryButtonText: { color: '#fff', fontSize: 16, fontWeight: '700', letterSpacing: 0.5 },
  errorText: { color: '#f87171', marginTop: 16, fontSize: 13 },
  paramRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  paramLabel: { color: colors.text, fontSize: 14 },
  paramValue: { color: colors.accent, fontSize: 14 },
  orb: {
    width: 160,
    height: 160,
    borderRadius: 80,
    backgroundColor: colors.accentDim,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 40,
    shadowColor: colors.accent,
    shadowOpacity: 0.6,
    shadowRadius: 40,
    shadowOffset: { width: 0, height: 0 },
    elevation: 20,
  },
  orbInner: { width: 80, height: 80, borderRadius: 40, backgroundColor: colors.accent },
  playButton: {
    width: 72,
    height: 72,
    borderRadius: 36,
    backgroundColor: colors.accent,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 24,
  },
  playButtonText: { fontSize: 28, color: '#fff' },
  shareButton: {
    paddingHorizontal: 28,
    paddingVertical: 12,
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: colors.accent,
  },
  shareButtonText: { color: colors.accent, fontWeight: '600' },
  hintText: { color: colors.muted, fontSize: 13, textAlign: 'center', marginTop: 20 },
});

